### ISSUE TITLE
mvn install -DskipTests -Pstreams errors out

### ISSUE THREAD

**Issue by reselbob** [Apicurio/apicurio-registry-demo#10]
Hi: I am trying to run the installation instructions in a Katacoda Ubuntu VM:

https://katacoda.com/courses/ubuntu/playground

(I am hoping to make a set of lessons show people how to use apicurio)

I broke up `mvn clean` and `mvn install`.

When I run `mvn install -DskipTests -Pstreams ` I get a bunch of errors. I am showing the end of the dump below. I am at a loss about how to make it better. If you need more information, please let me know.

Help? Please? Thanks!

```
.
.
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] 
[ERROR] 8 errors
[ERROR] role: org.apache.maven.plugin.Mojo
[ERROR] roleHint: io.quarkus:quarkus-maven-plugin:1.5.1.Final:build
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
```

**Comment by reselbob** [comment]
Turns out that I need to use the instructions here to get it up apicurio up and running:

`https://github.com/apicurio/apicurio-registry`

**Comment by EricWittmann** [comment]
Glad you got it working.  FYI another approach would be to use docker to get the registry up and running.

Note:  this demo is a bit old, we'll need to review it soon and make sure it still makes sense.

**Comment by reselbob** [comment]
I had a lot of problems getting the Docker version running. Haven’t be able to get it up and running yet.

Just to make sure we’re talking about the same instruction set, can you give me the URL that I can use as the authority for getting the Docker version up and running.

**Comment by EricWittmann** [comment]
Oh man, good point - I'm just now realizing that we don't really have documentation on how to run on Docker, only how to run on OpenShift.  I'll try to rectify that at some point.  However, for now, if you wanted to run the Streams variant of registry using docker, you can use this docker image:

https://hub.docker.com/layers/apicurio/apicurio-registry-streams/1.3.2.Final/images/sha256-d3bfb0d13498dedd563d7b45dfa2461e560bf0fbf08ff3767254bb8a198f4845?context=explore

You'll need to specify some ENV vars, which you can find here:

https://github.com/Apicurio/apicurio-registry/blob/1.3.x/distro/openshift-template/apicurio-registry-template-streams.yml#L82-L94

I think really you'd only need `QUARKUS_PROFILE`, `KAFKA_BOOTSTRAP_SERVERS`, and `APPLICATION_ID`.

The value for the profile should be `prod` and the value for the ApplicationId I think can be whatever you want.

**Comment by reselbob** [comment]
Maybe we can help each other. Since I am under contract with RH, maybe my manager will allow me to update the documentation for running Docker. (You probably just saw note coming at your from under under RH email.)

If, I can help out, I am more than willing to. Just let me know.

On Feb 24, 2021, at 9:51 AM, Eric Wittmann <notifications@github.com<mailto:notifications@github.com>> wrote:



Oh man, good point - I'm just now realizing that we don't really have documentation on how to run on Docker, only how to run on OpenShift. I'll try to rectify that at some point. However, for now, if you wanted to run the Streams variant of registry using docker, you can use this docker image:

https://hub.docker.com/layers/apicurio/apicurio-registry-streams/1.3.2.Final/images/sha256-d3bfb0d13498dedd563d7b45dfa2461e560bf0fbf08ff3767254bb8a198f4845?context=explore

You'll need to specify some ENV vars, which you can find here:

https://github.com/Apicurio/apicurio-registry/blob/1.3.x/distro/openshift-template/apicurio-registry-template-streams.yml#L82-L94

I think really you'd only need QUARKUS_PROFILE, KAFKA_BOOTSTRAP_SERVERS, and APPLICATION_ID.

The value for the profile should be prod and the value for the ApplicationId I think can be whatever you want.

**Comment by reselbob** [comment]
This instruction set works great!
https://www.apicur.io/registry/docs/apicurio-registry/1.3.3.Final/getting-started/assembly-installing-registry-docker.html
