### ISSUE TITLE
Issue while downloading the schema from Apicurio Registry

### ISSUE THREAD

**Issue by sks336** [Apicurio/apicurio-registry-demo#11]
1. I ran the Apicurio Registry using docker command.

`docker run --name apicurio_registry -d -p 8080:8080 apicurio/apicurio-registry-mem:latest`

2. Checkout your project and executed below command to invoke upload, which worked fine as Build was success and i could see the artifact in Apicurio Registry in the url [http://localhost:8080/ui/artifacts](http://localhost:8080/ui/artifacts)
`mvn clean install -DskipTests -Pupload`

3. But when i invoke the URL for download it gives error, like 
 `mvn clean install -DskipTests -Pdownload`

```
[ERROR] Failed to execute goal io.apicurio:apicurio-registry-maven-plugin:1.3.0.Final:download (default) on project apicurio-registry-demo: Exception thrown while downloading artifact [schema1] to /Users/sachin/workspace/skshukla/apicurio-registry-demo/target/schema1.avsc: java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Did i do anything wrong or missing anything here ?

Thanks,
-$

**Comment by sks336** [comment]
https://www.loom.com/share/0f9d17a009e04c088125a2e16f01cdaa?sharedAppSource=personal_library

**Comment by carlesarnal** [comment]
If I got everything right, the problem could be that you're running two different versions of the project since the tag `latest` refers to version `1.3.0.Final`  since we're no longer pushing the tag `latest` and branch master is on version 2.x. You must use either `latest-snapshot` which contains the latest changes from master or `latest-release` which contains the last stable release.

**Comment by sks336** [comment]
Thanks for the quick response Carlesarnal, But still the same. Great if you can try these at your end once.

1. `docker run --name apicurio_registry -d -p 8080:8080 apicurio/apicurio-registry-mem:latest-snapshot`
2. `git clone https://github.com/Apicurio/apicurio-registry-demo.git && cd apicurio-registry-demo`
3. `mvn clean install -DskipTests -Pupload`
4. `mvn clean install -DskipTests -Pdownload`

Thanks,
-$

**Comment by carlesarnal** [comment]
Oh sorry, I completely misread this. This is a known issue in older Registry versions. Adding jersey to the classpath should fix the issue. We still need to update our examples to 2.0.

**Comment by sks336** [comment]
Thanks a lot Carles.

-$

**Comment by EricWittmann** [comment]
I think this can be closed.  Please re-open if I'm wrong. :)

**Comment by sks336** [comment]
sure Eric, I confirm, it was working after your comment. I would close this
issue soon. thanks for the help.

-$
