### ISSUE TITLE
not able to run demo against minikube

### ISSUE THREAD

**Issue by rbaumgar** [Apicurio/apicurio-registry-demo#5]
I tried to run the demo against minikube with

> mvn exec:java -Dexec.mainClass="io.apicurio.registry.demo.Main" -Dboostrap.servers=192.168.39.83:32100 -Dregistry.url.1=192.168.39.83:30080 -Dregistry.url.2=192.168.39.83:30080

but Main tries to connect to 	bootstrap.servers = [localhost:9092]

**Comment by alesj** [comment]
Strange ... as this code is here
* https://github.com/Apicurio/apicurio-registry-demo/blob/master/src/main/java/io/apicurio/registry/demo/ApplicationImpl.java#L53

What if you run Main from IDE + add this sys prop ?

**Comment by alesj** [comment]
Ah ... @rbaumgar you have a typo ;-)
boostrap != bootstrap

**Comment by rbaumgar** [comment]
oh, it's because of the typo in the readme. thx!
